language: node_js
node_js: 8
cache: npm

git:
  submodules: false

script: npm run build:storybook

deploy:
  provider: pages
  local-dir: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
